### ISSUE TITLE
System environment for demo

### ISSUE THREAD

**Issue by hoihoic** [Jack-CV/PCN#4]
I tried to work on docker image from official caffe(bvlc/caffe:gpu) but it didnt work because of glog(maybe) and caffe version. I finally made it works on an image of nvidia/cuda:ubuntu14.04 with caffe 1.0.0 built by myself.

Could you upload binary file(libPCN.so) that can works on current official caffe docker image?

**Comment by Edwardmark** [comment]
@hoihoic hi, I met similar problem, would please give me some solution in details？

**Comment by Edwardmark** [comment]
@hoihoic hi, I met similar problem, would please give me some solution in details？

**Comment by Edwardmark** [comment]
@Jack-CV 
root@0b89d2cce164:/app/code# sh compile.sh picture
rm picture
rm: cannot remove 'picture': No such file or directory
compile picture
/usr/bin/ld: warning: libboost_system.so.1.54.0, needed by libPCN.so, not found (try using -rpath or -rpath-link)
/tmp/ccoYAtBX.o: In function `main':
picture.cpp:(.text.startup+0x6d): undefined reference to `PCN::PCN(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libPCN.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
libPCN.so: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
libPCN.so: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
done
I get this error,can you give me your caffe version or some boost version details?

**Comment by Jack-CV** [comment]
@Edwardmark My boost version is 1.54 and I use the latest caffe.

**Comment by hoihoic** [comment]
@Edwardmark I have built caffe 1.0(master branch with 1.0 tag, boost 1.54) manually on ubuntu 14.04.
I think it maybe caffe version problem on error with google base and copy layers form.

**Comment by Edwardmark** [comment]
@hoihoic Thank you very much!That helps.

**Comment by Edwardmark** [comment]
@hoihoic can you  give me a link of your docker image?

**Comment by Edwardmark** [comment]
@hoihoic can you give me a link of your docker image? It drives me crazy.

**Comment by Edwardmark** [comment]
@hoihoic would please tell me how do you complie glog?  
`sudo apt-get install libgoogle-glog-dev` didn't work for this demo?

**Comment by Edwardmark** [comment]
@hoihoic finally I compile the code successfully, I got:
`root@b50c61f18b38:/app/code# sh compile.sh picture
compile.sh: 1: compile.sh: i#!/usr/bin/en: not found

rm picture

compile picture

done ` 
but when I run it, I got the following error:  
`root@b50c61f18b38:/app/code# sh run.sh picture

./picture: error while loading shared libraries: libPCN.so: cannot open shared object file: No such file or directory`
when I run ls cmd, I got:  
`root@b50c61f18b38:/app/code# ls

PCN.dat PCN.h compile.sh glog-0.3.3 imgs libPCN.so picture picture.cpp run.sh v0.3.3.tar.gz video.cpp`

We can see that libPCN.so is right there, why I cannot run picture? Any advise?
Thank you very much.

**Comment by Edwardmark** [comment]
@hoihoic hi, never mind, it worked, it turns out that I forget to set the cafferoot.

**Comment by Edwardmark** [comment]
@Jack-CV I want to run your demo on GPU, what is your cuda and cudnn version?

**Comment by DecentMakeover** [comment]
@hoihoic Have you got the docker image working?

**Comment by Edwardmark** [comment]
@DecentMakeover you can try my docker https://github.com/Edwardmark/caffe-docker
